<?php
/**
 * @see https://silktide.com/tools/cookie-consent
 */

/**
 * Implements hook_init()
 */
function lightcookieconsent_init() {

  if (path_is_admin(current_path())) return;

  global $language;
  drupal_add_js(drupal_get_path('module', 'lightcookieconsent') . '/cookieconsent.min.js');

  $lang =  $language->language;
  $default = lightcookieconsent_get_default_config($lang);
  $options = json_encode(array(
      'message' => variable_get("lightcookieconsent_message_main_$lang", $default['message_main']),
      'learnMore'=> variable_get("lightcookieconsent_message_more_info_$lang", $default['message_more_info']),
      'dismiss'=> variable_get("lightcookieconsent_message_dismiss_$lang", $default['message_dismiss']),
      'link' => null,
      'theme' => 'light-top',
    ));
  $js = "window.cookieconsent_options = $options";
  drupal_add_js($js, 'inline');


}

/**
 * Implements hook_menu()
 */
function lightcookieconsent_menu() {
  return array(
    'admin/config/mazedia-cookie-consent' => array(
      'title' => t('Cookie consentement'),
      'description' => t('Configuration pour le consentement des cookie'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('lightcookieconsent_form'),
      'access arguments' => array('palais de tokyo config'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'lightcookieconsent.admin.forms.inc',
      'file path' => drupal_get_path('module', 'lightcookieconsent'),
    )
  );
}

/**
 * Configuration par défaut de cookie consent.
 * @param $language
 * @return mixed
 */
function lightcookieconsent_get_default_config($language) {
  $config = array(
    'en' => array(
      'message_main' => 'This website uses cookies to ensure you get the best experience on our website',
      'message_more_info' => 'More info',
      'message_dismiss' => "X",
      'more_info_link' => null,
    ),
    'fr' => array(
      'message_main' => 'Ce site utilise des cookies pour vous assurer la meilleure expérience utilisateur possible',
      'message_more_info' => "Plus d'informations",
      'message_dismiss' => "X",
      'more_info_link' => null
    )
  );
  return $config[$language];
}